# Generated by Django 5.2.8 on 2025-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_resume_resumeanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
