# Generated by Django 5.2.8 on 2025-11-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_resume_file_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="file_hash",
            new_name="text_hash",
        ),
    ]
