# Generated by Django 5.2.8 on 2025-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_file_hash_resume_text_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="text_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
