# Generated by Django 5.2.8 on 2025-11-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_resume_text_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumeanalysis",
            name="suggestions",
            field=models.JSONField(default=list),
        ),
    ]
